name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: ZAP Light Weight Scan
      uses: zaproxy/action-full-scan@v0.8.0
      with:
      target: 'https://www.zaproxy.org/'
